version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pfm
    container_name: pfm
    restart: unless-stopped
    working_dir: /var/www/html
    # ports:
    #   - 1021:8000
    # #   # - 9000:9000
    volumes:
      - .:/var/www/html
    networks:
      - traefik-public  
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=PathPrefix(`/api`)  || PathPrefix(`/docs`) 
      - traefik.http.services.home.loadbalancer.server.port=8000
    depends_on:
      - traefik

    # environment:
    #   XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal remote_port=9000"
    # stdin_open: true
    # tty: true
  
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost/phpmyadmin/
    ports:
      - 8081:80
    depends_on:
      - db
    # labels:
    #   - traefik.enable=false
    #   - traefik.http.routers.phpmyadmin.rule=PathPrefix(`/phpmyadmin`)
    #   # - traefik.http.middlewares.phpmyadmin-rewrite.replacepathregex.regex=^/phpmyadmin(/?.*)$
    #   # - traefik.http.middlewares.phpmyadmin-rewrite.replacepathregex.replacement=$$1
    #   # - traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-rewrite@docker
    #   - traefik.http.routers.phpmyadmin.entrypoints=web
    #   - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

    networks:
      - traefik-public  


 
  db:
    image: mariadb
    restart: unless-stopped
    container_name: database
    ports:
      - 3306:3306   #for debug on device
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: SuperSecret
    networks:
      - traefik-public  
    # labels:
    #   - traefik.enable=true
    #   - traefik.tcp.routers.mariadb.rule=HostSNI(`*`)
    #   - traefik.tcp.services.mariadb-svc.loadbalancer.server.port=3306



  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./middlewares.yml:/middlewares.yml

    networks:
      - traefik-public 

networks:
  traefik-public:  
#    external: true
    driver: bridge
