version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pfm
    container_name: pfm
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 1021:8000
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  db:
    image: mariadb
    restart: unless-stopped
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: SuperSecret
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
